'\" t
.\"     Title: dpcommence
.\"    Author: Ted Cowan
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 2019-03-08
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DPCOMMENCE" "3" "2019-03-08" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
dpcommence \- begins the processing of philosophers registered with *dpAddPhilosopher()* for the specified number of seconds.
.SH "SYNOPSIS"
.sp
\fB#include "dininglib.h"\fP
.sp
int dpCommence();
.SH "DESCRIPTION"
.sp
The \fBdpCommence()\fP function sleeps for the session time specified when \fBdpInitialize()\fP was previously called.  This function should only be called on the parent thread of the calling program.
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB\-1\fP
.RS 4
Failure and sets \fIerrno\fP to indicate the error.
.RE
.SH "ERRORS"
.sp
[EACCESS]
.RS 4
Library not initialized with \fBdpInitialize()\fP.
.RE
.SH "AUTHOR(S)"
.sp
\fBTed Cowan\fP
.RS 4
Author(s).
.RE