'\" t
.\"     Title: dpreleasechopstick
.\"    Author: Ted Cowan
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 2019-03-08
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DPRELEASECHOPSTICK" "3" "2019-03-08" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
dpreleasechopstick \- release a previously reserved chopstick for the calling thread.
.SH "SYNOPSIS"
.sp
\fB#include "dininglib.h"\fP
.sp
int dpReleaseChopstick(\fIint\fP \fIchopstick\fP);
.SH "DESCRIPTION"
.sp
The \fBdpReleaseChopstick()\fP function attempts to release the requested chopstick for the calling thread.  This function should only be called on the philosopher thread of a philosopher immediately to the left or right of the requested chopstick.
.sp
The argument \fInumber\fP is the number of chopstick to release.
.sp
This function must be called within a critical section.
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB\-1\fP
.RS 4
Failure and sets \fIerrno\fP to indicate the error.
.RE
.SH "ERRORS"
.sp
[EACCESS]
.RS 4
Library not initialized with \fBdpInitialize()\fP.
.RE
.sp
[EBUSY]
.RS 4
Another philosopher thread is in the process of reserving or releasing a chopstick.
.RE
.sp
[EINVAL]
.RS 4
This chopstick is not available to this philosopher, the philosopher is not registered or this chopstick was never previously reserved by this philosopher.
.RE
.SH "AUTHOR(S)"
.sp
\fBTed Cowan\fP
.RS 4
Author(s).
.RE